// <auto-generated />
using System;
using Foodie.Dal;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace Foodie.Dal.Migrations
{
    [DbContext(typeof(FoodieDbContext))]
    [Migration("20210424115742_Added the rest of the recipes")]
    partial class Addedtherestoftherecipes
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.13")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("Foodie.Dal.Entities.Recipe", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("Category")
                        .HasColumnType("int");

                    b.Property<TimeSpan>("CookingTime")
                        .HasColumnType("time");

                    b.Property<string>("Instruction")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<TimeSpan>("PreparationTime")
                        .HasColumnType("time");

                    b.HasKey("Id");

                    b.ToTable("Recipes");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Category = 225,
                            CookingTime = new TimeSpan(0, 0, 36, 0, 0),
                            Instruction = "In a large pot, heat olive oil and sauté the onions for 5 minutes. Add garlic and continue cooking for 1 more minute.;Add all the remaining ingredients, using 3 cups of chicken stock (except the lime juice) to the pot.;Bring to a simmer and allow to cook for 30 minutes, until the chicken is cooked through.;Stir in lime juice and serve with avocado and cilantro.",
                            Name = "Green Chicken Chili Soup",
                            PreparationTime = new TimeSpan(0, 0, 15, 0, 0)
                        },
                        new
                        {
                            Id = 2,
                            Category = 33,
                            CookingTime = new TimeSpan(0, 0, 25, 0, 0),
                            Instruction = "Sauté onions and peppers in olive oil over medium heat. Sauté until onions are just tender. Add garlic and cook for 2 more minutes. Add tomatoes, curry paste, chicken stock and chickpeas and bring to rapid simmer. Stir until paste is dissolved. Add coconut milk, fish sauce and lime juice, bring back to a simmer and allow to cook for 10 minutes.;Add chicken and cook for 10 minutes at a simmer until chicken is cooked through. Season with salt and add kale/spinach. Cook for 3 more minutes and serve as is or over cauliflower rice.;You may need to adjust the seasonings just a bit. Use less curry paste if you don't like it with a little “kick”.",
                            Name = "Coconut Curry Soup with Chicken, Chickpeas and Hearty Greens",
                            PreparationTime = new TimeSpan(0, 0, 10, 0, 0)
                        },
                        new
                        {
                            Id = 3,
                            Category = 33,
                            CookingTime = new TimeSpan(0, 0, 25, 0, 0),
                            Instruction = "Heat oil in a large pot set over medium-high heat. Add the onion and cook, stirring often until beginning to soften, about 4 minutes.;Add the garlic and bell peppers and cook, stirring often, until the garlic is fragrant and bell peppers begin to soften, about 2-3 more minutes longer.;Add the chicken stock, black beans, cumin, garlic powder, oregano, chili powder, salt and pepper. Turn the heat to high and bring to a boil. Once boiling, reduce the heat back down to medium-low and simmer for 10-15 minutes.;Using an immersion blender or stand blender, blend 1/3 of the soup. This step creates a thick, creamy texture to the soup.;Add the sausage to the soup and cook until the sausage is heated through.;Serve the soup topped with cilantro, sour cream and extra onion, if desired.",
                            Name = "Black Bean Soup",
                            PreparationTime = new TimeSpan(0, 0, 10, 0, 0)
                        },
                        new
                        {
                            Id = 4,
                            Category = 258,
                            CookingTime = new TimeSpan(0, 1, 35, 0, 0),
                            Instruction = "Pulse the butter, shortening flour and salt together in the base of a food processor (alternatively you can cut the butter and shortening into the flour by hand with a fork or pastry cutter) until butter and shortening are pea sized. Add the ice water one tablespoon at a time pulsing or mixing until dough just starts to come together. Do not over mix. Using your hands form a ball with the dough, wrap it in saran wrap and chill in the refrigerator for 30 minutes.;On a lightly floured surface roll out dough into a circle ¼-inch thick. Carefully press the dough into a tart pan, cutting away excess dough. Puncture dough with a fork a dozen times and chill for 30 minutes longer.;Preheat oven to 400°F. Cover the pie with a piece of foil and bake for 20 minutes. Remove the foil and continue to bake for another 10 minutes, or until crust is just set.;In a large saucepan with a tight fitting lid set over medium heat, melt 4 tablespoons butter and 2 tablespoons oil. Reduce heat to medium-low and add onions, leeks, scallions and shallots. Cover with a lid and cook for 10 minutes. Remove cover and continue to cook, stirring often, until onions turn a golden brown color. This process should take about 30 minutes. Remove from heat and allow to cool, about 20 minutes.;In a large bowl whisk together eggs, crème fraîche, salt, nutmeg, pepper and chives. Add the onion mixture to the egg mixture and stir until onions are evenly distributed. Pour into the tart crust and bake for 25-35 minutes, until eggs are set and the crust is golden brown.;Just before serving toss the arugula with desired amount of olive oil, salt and pepper. Add the salad to the top of the tart and serve.",
                            Name = "Five Onion Tart with Arugula Salad",
                            PreparationTime = new TimeSpan(0, 1, 5, 0, 0)
                        },
                        new
                        {
                            Id = 5,
                            Category = 354,
                            CookingTime = new TimeSpan(0, 0, 5, 0, 0),
                            Instruction = "To make the dressing place all the ingredients in a jar with a tight fitting lid. Shake vigorously until all ingredients are combined. Store in refrigerator for a week. Shake before each use.;To make the salad, place all ingredients in a large salad bowl. Drizzle with Italian dressing and toss to combine.",
                            Name = "Simple Italian Salad",
                            PreparationTime = new TimeSpan(0, 0, 10, 0, 0)
                        },
                        new
                        {
                            Id = 6,
                            Category = 4,
                            CookingTime = new TimeSpan(0, 0, 30, 0, 0),
                            Instruction = "Preheat oven to 375°F.;Butter each half of the English muffins with ½ tablespoon butter. Arrange muffins on a large baking sheet and place them on the center rack. Bake until golden and crispy, about 10 minutes.;While muffins are toasting, heat the hollandaise sauce and poached eggs according to respective recipe instructions.;Arrange the toasted English muffins on a large platter. Top each half with ham or Canadian bacon. Top with a poached egg. Drizzle hollandaise sauce over the entire platter and top with fresh herbs. Serve immediately.",
                            Name = "Eggs Benedict",
                            PreparationTime = new TimeSpan(0, 0, 20, 0, 0)
                        },
                        new
                        {
                            Id = 7,
                            Category = 484,
                            CookingTime = new TimeSpan(0, 0, 10, 0, 0),
                            Instruction = "Fill a large pot with 4-5 inches of water. Bring to a low boil.;Working with one egg at a time, crack the egg into a mesh strainer over your sink. Shake the strainer to get rid of any egg whites that are already separated. Transfer egg to a small bowl.;Carefully lower the egg into the simmering water by tipping to bowl sideways as close to the edge of the water as you can get, allowing the egg to slip out of the bowl.;Cook egg for 3 minutes. Remove using a slotted spoon and transfer to a bowl of cold water or serve immediately.",
                            Name = "Poached Eggs",
                            PreparationTime = new TimeSpan(0, 0, 5, 0, 0)
                        },
                        new
                        {
                            Id = 8,
                            Category = 8,
                            CookingTime = new TimeSpan(0, 0, 25, 0, 0),
                            Instruction = "Preheat oven to 400° F.;Grab three shallow bowls, or rimmed plates, large enough to fit the size of your chicken breast. In one bowl beat the eggs until smooth. In the second bowl, place the flour and in the third bowl, mix together the Panko, bread crumbs and the parmesan cheese until fully combined.;In a small bowl mix together the garlic powder, sea salt salt, pepper and Italian seasoning. Season chicken filets on both sides with the seasoning. Dredge each filleted breast in the flour and gently shake off excess, then dip in the egg and let the excess drip off, then dredge on both sides in the bread crumbs, gently pressing to coat completely.;Heat 1/4 of the oil in a 12” skillet over medium-high heat until smoking. Add 3 chicken breast fillets and cook until golden brown, about 2 minutes per side. Transfer to a baking sheet. Add remaining oil and heat until smoking. Repeat the process with remaining chicken and transfer to the baking sheet.;Top each breast with 3-4 tablespoons of tomato sauce and 2 slices each of the mozzarella. Bake in the oven until the chicken is cooked through (chicken is done when the thickest part of the chicken reads 165°F with an instant read thermometer.) and the cheese is melted, about 10-14 minutes. Remove from the oven and garnish with basil, extra parmesan and red pepper flakes if desired.",
                            Name = "Chicken Parmesan",
                            PreparationTime = new TimeSpan(0, 0, 20, 0, 0)
                        },
                        new
                        {
                            Id = 9,
                            Category = 264,
                            CookingTime = new TimeSpan(0, 0, 20, 0, 0),
                            Instruction = "Fill a large pot with 4 quarts of water and add 2 teaspoons of salt. Bring to a boil over high heat. Add the pasta and cook according to package instructions, about 8-12 minutes, drain.;While the water is heating up, heat 1 tablespoon olive oil in a large skillet, set over medium high heat. Add the shallots and carrots stirring until softened, about 5 minutes. Remove from the pan onto a plate. Add remaining olive oil to the pan, swirl to coat and add the zucchini and squash in a single layer. Cook for 2-3 minutes on each side, until golden brown. Remove the zucchini onto the plate with the carrots and shallots.;Add the butter to the pan. When it begins to bubble, about 2 minutes, add the cheese, milk, dried basil, garlic powder, pepper and the remaining 1/4 teaspoon of salt. Whisk until combined and smooth. Note: if you are using pre-grated parmesan the sauce might not get completely smooth and will result in a more grainy sauce, but will still taste lovely.;Add in the sun dried tomatoes and cherry tomatoes and toss until warmed through.;Drain the pasta, then immediately add it to the sauce and toss to coat. Add a splash more milk if the sauce is too thick or a sprinkle of extra parm if the sauce is too thin. Serve with fresh basil or flat leaf parsley and crushed red pepper flakes if desired.",
                            Name = "Pasta Primavera",
                            PreparationTime = new TimeSpan(0, 0, 20, 0, 0)
                        },
                        new
                        {
                            Id = 10,
                            Category = 304,
                            CookingTime = new TimeSpan(0, 0, 45, 0, 0),
                            Instruction = "Preheat oven to 350°F.;Begin by making the crumb topping. Combine the flour sugar, coconut, pecans and salt in a bowl. Using a cheese grater grate butter into the dry mix.** toss with a fork until butter and dry ingredients are evenly mixed. The crumble will appear to be dry, this method ensures an even middle ribbon of goodness and topping. Store the crumble in the refrigerator while preparing your batter.;For the cake batter sift flour, baking powder, baking soda and salt into a medium sized bowl and set aside. In a stand mixer, or by hand, whisk the softened butter until light and fluffy. Add the sugar slowly, followed by the eggs one at a time fully incorporating with each addition.;Add ⅓ of the sifted dry ingredients and ⅓ cup of the sour cream to the bowl of the stand mixer. Beat until they’re fully incorporated, then add the remaining sour cream and dry ingredients. Beat on high for about three minutes.;In a well-greased or parchment lined 9x9 baking dish add half of the batter followed by half of the crumble. Add the remaining batter and crumb topping. Bake for 45 min to an hour in a preheated. Check for doneness with a toothpick, which should come out clean. Cool on a wire rack for 30 minutes before serving.",
                            Name = "Sour Cream Coffee Cake",
                            PreparationTime = new TimeSpan(0, 0, 25, 0, 0)
                        },
                        new
                        {
                            Id = 11,
                            Category = 272,
                            CookingTime = new TimeSpan(0, 0, 10, 0, 0),
                            Instruction = "In a small sauce pan heat milk, sugar, salt and vanilla over medium-low heat until sugar and salt are completely dissolved. Make sure the milk does not come to a boil. Add the chocolate in pieces, whisking until completely incorporated. Remove from heat.;Once removed from heat, stir in bourbon, frangelico and Irish cream. Serve immediately with marshmallows.",
                            Name = "Adult Hot Chocolate",
                            PreparationTime = new TimeSpan(0, 0, 5, 0, 0)
                        },
                        new
                        {
                            Id = 12,
                            Category = 272,
                            CookingTime = new TimeSpan(0, 0, 12, 0, 0),
                            Instruction = "Adjust oven rack to middle position and heat oven to 325° F. Line 2 baking sheets with parchment paper. We recommend using a kitchen scale for this recipe and weighing out the ingredients.;Whisk flour, cocoa, baking powder, baking soda, and salt together in bowl.;Whisk brown sugar; eggs; and vanilla together in large bowl. Combine chocolate and butter in bowl and microwave at 50 percent power, stirring occasionally, until melted, 2 to 3 minutes.;Whisk chocolate mixture into egg mixture until combined. Fold in flour mixture until no dry streaks remain. Let dough sit at room temperature for 10 minutes. Do not refrigerate.;Place granulated sugar and confectioners’ sugar in separate shallow dishes. Working with 1 rounded tablespoon of dough at a time, from the scoop, drop dough balls directly into granulated sugar and roll to coat. Transfer dough balls to confectioners’ sugar and roll to give each a heavy even coat. Evenly space dough balls on prepared sheets.;Bake cookies, 1 sheet at a time, until puffed and cracked and edges have begun to set but centers are still soft (cookies will look raw between cracks and seem underdone), about 12 minutes, rotating sheet halfway through baking. Let cool completely on sheet.;Using a stand mixer fitted with the paddle blade attachment, beat the butter until smooth and fluffy.;Add the powdered sugar a little bit at a time, with mixer running continuously.;Add in the cream and peppermint extract. Whip until completely smooth.;Place the unwrapped candy canes in a zip-lock bag. Using a rolling pin, crush the candy into small pieces. Pour the crushed candy onto a plate.;Once cookies have cooled completely, spread 2 tbsp frosting on the underside of one cookie and top with another. Roll edges into the crushed candy cane. Repeat for remaining cookies.",
                            Name = "Crinkle Cookies with Peppermint Cream",
                            PreparationTime = new TimeSpan(0, 0, 30, 0, 0)
                        });
                });

            modelBuilder.Entity("Foodie.Dal.Entities.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("int");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Email")
                        .HasColumnType("nvarchar(256)")
                        .HasMaxLength(256);

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("bit");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("bit");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("NormalizedEmail")
                        .HasColumnType("nvarchar(256)")
                        .HasMaxLength(256);

                    b.Property<string>("NormalizedUserName")
                        .HasColumnType("nvarchar(256)")
                        .HasMaxLength(256);

                    b.Property<string>("PasswordHash")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("bit");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("bit");

                    b.Property<string>("UserName")
                        .HasColumnType("nvarchar(256)")
                        .HasMaxLength(256);

                    b.HasKey("Id");

                    b.HasIndex("NormalizedEmail")
                        .HasName("EmailIndex");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasName("UserNameIndex")
                        .HasFilter("[NormalizedUserName] IS NOT NULL");

                    b.ToTable("AspNetUsers");
                });

            modelBuilder.Entity("Foodie.Dal.Entities.UserRecipe", b =>
                {
                    b.Property<int>("RecipeId")
                        .HasColumnType("int");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("RecipeId", "UserId");

                    b.HasIndex("UserId");

                    b.ToTable("UserRecipes");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRole<int>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(256)")
                        .HasMaxLength(256);

                    b.Property<string>("NormalizedName")
                        .HasColumnType("nvarchar(256)")
                        .HasMaxLength(256);

                    b.HasKey("Id");

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasName("RoleNameIndex")
                        .HasFilter("[NormalizedName] IS NOT NULL");

                    b.ToTable("AspNetRoles");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<int>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("RoleId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetRoleClaims");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<int>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserClaims");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<int>", b =>
                {
                    b.Property<string>("LoginProvider")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ProviderKey")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ProviderDisplayName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("LoginProvider", "ProviderKey");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserLogins");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<int>", b =>
                {
                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.Property<int>("RoleId")
                        .HasColumnType("int");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetUserRoles");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<int>", b =>
                {
                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.Property<string>("LoginProvider")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Value")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("UserId", "LoginProvider", "Name");

                    b.ToTable("AspNetUserTokens");
                });

            modelBuilder.Entity("Foodie.Dal.Entities.Recipe", b =>
                {
                    b.OwnsMany("Foodie.Dal.Entities.Ingredient", "Ingredients", b1 =>
                        {
                            b1.Property<int>("RecipeId")
                                .HasColumnType("int");

                            b1.Property<int>("Id")
                                .ValueGeneratedOnAdd()
                                .HasColumnType("int")
                                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                            b1.Property<double?>("Amount")
                                .HasColumnType("float");

                            b1.Property<int>("Measurement")
                                .HasColumnType("int");

                            b1.Property<string>("Name")
                                .IsRequired()
                                .HasColumnType("nvarchar(max)");

                            b1.HasKey("RecipeId", "Id");

                            b1.ToTable("Ingredient");

                            b1.WithOwner()
                                .HasForeignKey("RecipeId");

                            b1.HasData(
                                new
                                {
                                    RecipeId = 1,
                                    Id = 1,
                                    Amount = 2.0,
                                    Measurement = 3,
                                    Name = "Olive oil"
                                },
                                new
                                {
                                    RecipeId = 1,
                                    Id = 2,
                                    Amount = 1.0,
                                    Measurement = 0,
                                    Name = "Onion"
                                },
                                new
                                {
                                    RecipeId = 1,
                                    Id = 3,
                                    Amount = 4.0,
                                    Measurement = 0,
                                    Name = "Garlic cloves"
                                },
                                new
                                {
                                    RecipeId = 1,
                                    Id = 4,
                                    Amount = 2.0,
                                    Measurement = 5,
                                    Name = "Chicken stock"
                                },
                                new
                                {
                                    RecipeId = 1,
                                    Id = 5,
                                    Amount = 1.0,
                                    Measurement = 9,
                                    Name = "White beans"
                                },
                                new
                                {
                                    RecipeId = 1,
                                    Id = 6,
                                    Amount = 1.0,
                                    Measurement = 9,
                                    Name = "Salsa verde"
                                },
                                new
                                {
                                    RecipeId = 1,
                                    Id = 7,
                                    Amount = 1.0,
                                    Measurement = 9,
                                    Name = "Green chilis"
                                },
                                new
                                {
                                    RecipeId = 1,
                                    Id = 8,
                                    Amount = 1.0,
                                    Measurement = 0,
                                    Name = "Green bell pepper"
                                },
                                new
                                {
                                    RecipeId = 1,
                                    Id = 9,
                                    Amount = 1.0,
                                    Measurement = 0,
                                    Name = "Jalapeno"
                                },
                                new
                                {
                                    RecipeId = 1,
                                    Id = 10,
                                    Amount = 0.68000000000000005,
                                    Measurement = 11,
                                    Name = "Chicken breast"
                                },
                                new
                                {
                                    RecipeId = 1,
                                    Id = 11,
                                    Amount = 1.0,
                                    Measurement = 1,
                                    Name = "Cumin"
                                },
                                new
                                {
                                    RecipeId = 1,
                                    Id = 12,
                                    Amount = 1.0,
                                    Measurement = 1,
                                    Name = "Chili powder"
                                },
                                new
                                {
                                    RecipeId = 1,
                                    Id = 13,
                                    Amount = 1.0,
                                    Measurement = 1,
                                    Name = "Salt"
                                },
                                new
                                {
                                    RecipeId = 1,
                                    Id = 14,
                                    Amount = 2.0,
                                    Measurement = 3,
                                    Name = "Lime juice"
                                },
                                new
                                {
                                    RecipeId = 2,
                                    Id = 1,
                                    Amount = 1.0,
                                    Measurement = 3,
                                    Name = "Olive oil"
                                },
                                new
                                {
                                    RecipeId = 2,
                                    Id = 2,
                                    Amount = 1.0,
                                    Measurement = 0,
                                    Name = "onion"
                                },
                                new
                                {
                                    RecipeId = 2,
                                    Id = 3,
                                    Amount = 2.0,
                                    Measurement = 0,
                                    Name = "Red bell pepper"
                                },
                                new
                                {
                                    RecipeId = 2,
                                    Id = 4,
                                    Amount = 4.0,
                                    Measurement = 0,
                                    Name = "Garlic cloves"
                                },
                                new
                                {
                                    RecipeId = 2,
                                    Id = 5,
                                    Amount = 1.0,
                                    Measurement = 9,
                                    Name = "Diced Tomatoe"
                                },
                                new
                                {
                                    RecipeId = 2,
                                    Id = 6,
                                    Amount = 1.0,
                                    Measurement = 9,
                                    Name = "Chickpea"
                                },
                                new
                                {
                                    RecipeId = 2,
                                    Id = 7,
                                    Amount = 4.0,
                                    Measurement = 5,
                                    Name = "Chicken stock"
                                },
                                new
                                {
                                    RecipeId = 2,
                                    Id = 8,
                                    Amount = 2.0,
                                    Measurement = 9,
                                    Name = "Full fat coconut milk"
                                },
                                new
                                {
                                    RecipeId = 2,
                                    Id = 9,
                                    Amount = 2.0,
                                    Measurement = 3,
                                    Name = "Red curry paste"
                                },
                                new
                                {
                                    RecipeId = 2,
                                    Id = 10,
                                    Amount = 2.0,
                                    Measurement = 1,
                                    Name = "Fish sauce"
                                },
                                new
                                {
                                    RecipeId = 2,
                                    Id = 11,
                                    Measurement = 12,
                                    Name = "Lemon juice"
                                },
                                new
                                {
                                    RecipeId = 2,
                                    Id = 12,
                                    Amount = 0.68000000000000005,
                                    Measurement = 11,
                                    Name = "Chicken breasts"
                                },
                                new
                                {
                                    RecipeId = 2,
                                    Id = 13,
                                    Amount = 2.0,
                                    Measurement = 5,
                                    Name = "Kale"
                                },
                                new
                                {
                                    RecipeId = 2,
                                    Id = 14,
                                    Measurement = 12,
                                    Name = "Salt"
                                },
                                new
                                {
                                    RecipeId = 3,
                                    Id = 1,
                                    Amount = 2.0,
                                    Measurement = 3,
                                    Name = "Extra virgin olive oil"
                                },
                                new
                                {
                                    RecipeId = 3,
                                    Id = 2,
                                    Amount = 1.0,
                                    Measurement = 0,
                                    Name = "Red onion"
                                },
                                new
                                {
                                    RecipeId = 3,
                                    Id = 3,
                                    Amount = 4.0,
                                    Measurement = 0,
                                    Name = "Garlic cloves"
                                },
                                new
                                {
                                    RecipeId = 3,
                                    Id = 4,
                                    Amount = 1.0,
                                    Measurement = 0,
                                    Name = "Red bell peppers"
                                },
                                new
                                {
                                    RecipeId = 3,
                                    Id = 5,
                                    Amount = 1.0,
                                    Measurement = 0,
                                    Name = "Green bell pepper"
                                },
                                new
                                {
                                    RecipeId = 3,
                                    Id = 6,
                                    Amount = 4.0,
                                    Measurement = 5,
                                    Name = "Chicken stock"
                                },
                                new
                                {
                                    RecipeId = 3,
                                    Id = 7,
                                    Amount = 3.0,
                                    Measurement = 9,
                                    Name = "Black bean"
                                },
                                new
                                {
                                    RecipeId = 3,
                                    Id = 8,
                                    Amount = 2.0,
                                    Measurement = 1,
                                    Name = "Ground cumin"
                                },
                                new
                                {
                                    RecipeId = 3,
                                    Id = 9,
                                    Amount = 2.0,
                                    Measurement = 1,
                                    Name = "Garlic powder"
                                },
                                new
                                {
                                    RecipeId = 3,
                                    Id = 10,
                                    Amount = 2.0,
                                    Measurement = 1,
                                    Name = "Dried oregano"
                                },
                                new
                                {
                                    RecipeId = 3,
                                    Id = 11,
                                    Amount = 1.0,
                                    Measurement = 3,
                                    Name = "Chili powder"
                                },
                                new
                                {
                                    RecipeId = 3,
                                    Id = 12,
                                    Amount = 1.0,
                                    Measurement = 1,
                                    Name = "Kosher salt"
                                },
                                new
                                {
                                    RecipeId = 3,
                                    Id = 13,
                                    Amount = 0.5,
                                    Measurement = 1,
                                    Name = "Freshly ground pepper"
                                },
                                new
                                {
                                    RecipeId = 3,
                                    Id = 14,
                                    Amount = 0.45000000000000001,
                                    Measurement = 11,
                                    Name = "Smoked sausage"
                                },
                                new
                                {
                                    RecipeId = 3,
                                    Id = 15,
                                    Measurement = 12,
                                    Name = "Cilantro"
                                },
                                new
                                {
                                    RecipeId = 3,
                                    Id = 16,
                                    Measurement = 12,
                                    Name = "Sour cream"
                                },
                                new
                                {
                                    RecipeId = 4,
                                    Id = 1,
                                    Amount = 0.5,
                                    Measurement = 5,
                                    Name = "Unsalted butter"
                                },
                                new
                                {
                                    RecipeId = 4,
                                    Id = 2,
                                    Amount = 0.5,
                                    Measurement = 5,
                                    Name = "Vegetable shortening"
                                },
                                new
                                {
                                    RecipeId = 4,
                                    Id = 3,
                                    Amount = 2.0,
                                    Measurement = 5,
                                    Name = "All purpose flour"
                                },
                                new
                                {
                                    RecipeId = 4,
                                    Id = 4,
                                    Amount = 0.5,
                                    Measurement = 1,
                                    Name = "Sea salt"
                                },
                                new
                                {
                                    RecipeId = 4,
                                    Id = 5,
                                    Amount = 5.0,
                                    Measurement = 3,
                                    Name = "Ice water"
                                },
                                new
                                {
                                    RecipeId = 4,
                                    Id = 6,
                                    Amount = 4.0,
                                    Measurement = 3,
                                    Name = "Butter"
                                },
                                new
                                {
                                    RecipeId = 4,
                                    Id = 7,
                                    Amount = 2.0,
                                    Measurement = 3,
                                    Name = "Olive oil"
                                },
                                new
                                {
                                    RecipeId = 4,
                                    Id = 8,
                                    Amount = 1.0,
                                    Measurement = 0,
                                    Name = "Yellow onion"
                                },
                                new
                                {
                                    RecipeId = 4,
                                    Id = 9,
                                    Amount = 2.0,
                                    Measurement = 0,
                                    Name = "Leeks"
                                },
                                new
                                {
                                    RecipeId = 4,
                                    Id = 10,
                                    Amount = 4.0,
                                    Measurement = 0,
                                    Name = "Green onion"
                                },
                                new
                                {
                                    RecipeId = 4,
                                    Id = 11,
                                    Amount = 2.0,
                                    Measurement = 0,
                                    Name = "Shallots"
                                },
                                new
                                {
                                    RecipeId = 4,
                                    Id = 12,
                                    Amount = 4.0,
                                    Measurement = 0,
                                    Name = "Eggs"
                                },
                                new
                                {
                                    RecipeId = 4,
                                    Id = 13,
                                    Amount = 0.33000000000000002,
                                    Measurement = 5,
                                    Name = "Crème fraîche"
                                },
                                new
                                {
                                    RecipeId = 4,
                                    Id = 14,
                                    Measurement = 12,
                                    Name = "Salt"
                                },
                                new
                                {
                                    RecipeId = 4,
                                    Id = 15,
                                    Amount = 0.25,
                                    Measurement = 1,
                                    Name = "Nutmeg"
                                },
                                new
                                {
                                    RecipeId = 4,
                                    Id = 16,
                                    Measurement = 12,
                                    Name = "Pepper"
                                },
                                new
                                {
                                    RecipeId = 4,
                                    Id = 17,
                                    Amount = 0.5,
                                    Measurement = 5,
                                    Name = "Chives"
                                },
                                new
                                {
                                    RecipeId = 4,
                                    Id = 18,
                                    Amount = 4.0,
                                    Measurement = 5,
                                    Name = "Arugula"
                                },
                                new
                                {
                                    RecipeId = 5,
                                    Id = 1,
                                    Amount = 1.0,
                                    Measurement = 13,
                                    Name = "Leafy romaine lettuce"
                                },
                                new
                                {
                                    RecipeId = 5,
                                    Id = 2,
                                    Amount = 0.5,
                                    Measurement = 0,
                                    Name = "Red onion"
                                },
                                new
                                {
                                    RecipeId = 5,
                                    Id = 3,
                                    Amount = 0.5,
                                    Measurement = 5,
                                    Name = "Parmesan cheese"
                                },
                                new
                                {
                                    RecipeId = 5,
                                    Id = 4,
                                    Amount = 1.0,
                                    Measurement = 5,
                                    Name = "Peperoncini"
                                },
                                new
                                {
                                    RecipeId = 5,
                                    Id = 5,
                                    Amount = 0.5,
                                    Measurement = 5,
                                    Name = "Black olives"
                                },
                                new
                                {
                                    RecipeId = 5,
                                    Id = 6,
                                    Amount = 1.0,
                                    Measurement = 6,
                                    Name = "Cherry tomatoes"
                                },
                                new
                                {
                                    RecipeId = 5,
                                    Id = 7,
                                    Measurement = 12,
                                    Name = "Pepper"
                                },
                                new
                                {
                                    RecipeId = 5,
                                    Id = 8,
                                    Measurement = 12,
                                    Name = "Croutons"
                                },
                                new
                                {
                                    RecipeId = 5,
                                    Id = 9,
                                    Amount = 1.0,
                                    Measurement = 1,
                                    Name = "Garlic powder"
                                },
                                new
                                {
                                    RecipeId = 5,
                                    Id = 10,
                                    Amount = 1.0,
                                    Measurement = 1,
                                    Name = "Dried oregano"
                                },
                                new
                                {
                                    RecipeId = 5,
                                    Id = 11,
                                    Amount = 1.0,
                                    Measurement = 1,
                                    Name = "Dried basil"
                                },
                                new
                                {
                                    RecipeId = 5,
                                    Id = 12,
                                    Amount = 0.5,
                                    Measurement = 1,
                                    Name = "Sea salt"
                                },
                                new
                                {
                                    RecipeId = 5,
                                    Id = 13,
                                    Amount = 0.5,
                                    Measurement = 5,
                                    Name = "Extra virgin olive oil"
                                },
                                new
                                {
                                    RecipeId = 5,
                                    Id = 14,
                                    Amount = 2.0,
                                    Measurement = 3,
                                    Name = "Red wine vinegar"
                                },
                                new
                                {
                                    RecipeId = 6,
                                    Id = 1,
                                    Amount = 12.0,
                                    Measurement = 0,
                                    Name = "Poached eggs"
                                },
                                new
                                {
                                    RecipeId = 6,
                                    Id = 2,
                                    Measurement = 12,
                                    Name = "Hollandaise sauce"
                                },
                                new
                                {
                                    RecipeId = 6,
                                    Id = 3,
                                    Amount = 6.0,
                                    Measurement = 0,
                                    Name = "English muffins"
                                },
                                new
                                {
                                    RecipeId = 6,
                                    Id = 4,
                                    Amount = 3.0,
                                    Measurement = 3,
                                    Name = "Salted butter"
                                },
                                new
                                {
                                    RecipeId = 6,
                                    Id = 5,
                                    Measurement = 12,
                                    Name = "Ham"
                                },
                                new
                                {
                                    RecipeId = 6,
                                    Id = 6,
                                    Amount = 0.25,
                                    Measurement = 5,
                                    Name = "Fresh herbs"
                                },
                                new
                                {
                                    RecipeId = 7,
                                    Id = 1,
                                    Amount = 1.0,
                                    Measurement = 0,
                                    Name = "Egg"
                                },
                                new
                                {
                                    RecipeId = 8,
                                    Id = 1,
                                    Amount = 3.0,
                                    Measurement = 0,
                                    Name = "Egg"
                                },
                                new
                                {
                                    RecipeId = 8,
                                    Id = 2,
                                    Amount = 0.5,
                                    Measurement = 5,
                                    Name = "All purpose flour"
                                },
                                new
                                {
                                    RecipeId = 8,
                                    Id = 3,
                                    Amount = 0.75,
                                    Measurement = 5,
                                    Name = "Panko breadcrumbs"
                                },
                                new
                                {
                                    RecipeId = 8,
                                    Id = 4,
                                    Amount = 0.33000000000000002,
                                    Measurement = 5,
                                    Name = "Bread crumbs"
                                },
                                new
                                {
                                    RecipeId = 8,
                                    Id = 5,
                                    Amount = 0.75,
                                    Measurement = 5,
                                    Name = "Parmesan cheese"
                                },
                                new
                                {
                                    RecipeId = 8,
                                    Id = 6,
                                    Amount = 1.0,
                                    Measurement = 1,
                                    Name = "Garlic powder"
                                },
                                new
                                {
                                    RecipeId = 8,
                                    Id = 7,
                                    Amount = 1.5,
                                    Measurement = 1,
                                    Name = "Sea salt"
                                },
                                new
                                {
                                    RecipeId = 8,
                                    Id = 8,
                                    Amount = 0.5,
                                    Measurement = 1,
                                    Name = "Pepper"
                                },
                                new
                                {
                                    RecipeId = 8,
                                    Id = 9,
                                    Amount = 1.0,
                                    Measurement = 1,
                                    Name = "Italian seasoning"
                                },
                                new
                                {
                                    RecipeId = 8,
                                    Id = 10,
                                    Amount = 3.0,
                                    Measurement = 0,
                                    Name = "Chicken breast"
                                },
                                new
                                {
                                    RecipeId = 8,
                                    Id = 11,
                                    Amount = 0.5,
                                    Measurement = 5,
                                    Name = "Extra virgin olive oil"
                                },
                                new
                                {
                                    RecipeId = 8,
                                    Id = 12,
                                    Amount = 1.0,
                                    Measurement = 10,
                                    Name = "Marinara sauce"
                                },
                                new
                                {
                                    RecipeId = 8,
                                    Id = 13,
                                    Amount = 8.0,
                                    Measurement = 4,
                                    Name = "Mozzarella cheese"
                                },
                                new
                                {
                                    RecipeId = 8,
                                    Id = 14,
                                    Amount = 2.0,
                                    Measurement = 3,
                                    Name = "Basil"
                                },
                                new
                                {
                                    RecipeId = 8,
                                    Id = 15,
                                    Measurement = 12,
                                    Name = "Red pepper flakes"
                                },
                                new
                                {
                                    RecipeId = 9,
                                    Id = 1,
                                    Amount = 2.25,
                                    Measurement = 1,
                                    Name = "Sea salt"
                                },
                                new
                                {
                                    RecipeId = 9,
                                    Id = 2,
                                    Amount = 12.0,
                                    Measurement = 4,
                                    Name = "Pasta of your choice"
                                },
                                new
                                {
                                    RecipeId = 9,
                                    Id = 3,
                                    Amount = 2.0,
                                    Measurement = 3,
                                    Name = "Extra virgin olive oil"
                                },
                                new
                                {
                                    RecipeId = 9,
                                    Id = 4,
                                    Amount = 1.0,
                                    Measurement = 0,
                                    Name = "shallot"
                                },
                                new
                                {
                                    RecipeId = 9,
                                    Id = 5,
                                    Amount = 1.0,
                                    Measurement = 0,
                                    Name = "Carrot"
                                },
                                new
                                {
                                    RecipeId = 9,
                                    Id = 6,
                                    Amount = 1.0,
                                    Measurement = 0,
                                    Name = "Zucchini"
                                },
                                new
                                {
                                    RecipeId = 9,
                                    Id = 7,
                                    Amount = 1.0,
                                    Measurement = 0,
                                    Name = "Yellow summer squash"
                                },
                                new
                                {
                                    RecipeId = 9,
                                    Id = 8,
                                    Amount = 6.0,
                                    Measurement = 3,
                                    Name = "Unsalted butter"
                                },
                                new
                                {
                                    RecipeId = 9,
                                    Id = 9,
                                    Amount = 0.75,
                                    Measurement = 5,
                                    Name = "Parmesan cheese"
                                },
                                new
                                {
                                    RecipeId = 9,
                                    Id = 10,
                                    Amount = 0.5,
                                    Measurement = 5,
                                    Name = "Whole milk"
                                },
                                new
                                {
                                    RecipeId = 9,
                                    Id = 11,
                                    Amount = 1.0,
                                    Measurement = 1,
                                    Name = "Dried basil"
                                },
                                new
                                {
                                    RecipeId = 9,
                                    Id = 12,
                                    Amount = 0.5,
                                    Measurement = 1,
                                    Name = "Garlic powder"
                                },
                                new
                                {
                                    RecipeId = 9,
                                    Id = 13,
                                    Amount = 0.33000000000000002,
                                    Measurement = 5,
                                    Name = "Sun dried tomatoes"
                                },
                                new
                                {
                                    RecipeId = 9,
                                    Id = 14,
                                    Amount = 1.5,
                                    Measurement = 5,
                                    Name = "Cherry tomatoes,"
                                },
                                new
                                {
                                    RecipeId = 10,
                                    Id = 1,
                                    Amount = 2.0,
                                    Measurement = 5,
                                    Name = "White flour"
                                },
                                new
                                {
                                    RecipeId = 10,
                                    Id = 2,
                                    Amount = 1.5,
                                    Measurement = 1,
                                    Name = "Baking powder"
                                },
                                new
                                {
                                    RecipeId = 10,
                                    Id = 3,
                                    Amount = 1.5,
                                    Measurement = 1,
                                    Name = "Baking soda"
                                },
                                new
                                {
                                    RecipeId = 10,
                                    Id = 4,
                                    Amount = 0.5,
                                    Measurement = 1,
                                    Name = "Salt"
                                },
                                new
                                {
                                    RecipeId = 10,
                                    Id = 5,
                                    Amount = 1.0,
                                    Measurement = 5,
                                    Name = "Unsalted butter"
                                },
                                new
                                {
                                    RecipeId = 10,
                                    Id = 6,
                                    Amount = 2.0,
                                    Measurement = 0,
                                    Name = "Egg"
                                },
                                new
                                {
                                    RecipeId = 10,
                                    Id = 7,
                                    Amount = 1.0,
                                    Measurement = 5,
                                    Name = "White sugar"
                                },
                                new
                                {
                                    RecipeId = 10,
                                    Id = 8,
                                    Amount = 1.0,
                                    Measurement = 5,
                                    Name = "Sour cream"
                                },
                                new
                                {
                                    RecipeId = 10,
                                    Id = 9,
                                    Amount = 0.25,
                                    Measurement = 5,
                                    Name = "All purpose flour"
                                },
                                new
                                {
                                    RecipeId = 10,
                                    Id = 10,
                                    Amount = 1.0,
                                    Measurement = 5,
                                    Name = "Brown sugar"
                                },
                                new
                                {
                                    RecipeId = 10,
                                    Id = 11,
                                    Amount = 0.5,
                                    Measurement = 5,
                                    Name = "Flaked coconut"
                                },
                                new
                                {
                                    RecipeId = 10,
                                    Id = 12,
                                    Amount = 1.0,
                                    Measurement = 5,
                                    Name = "Toasted walnuts"
                                },
                                new
                                {
                                    RecipeId = 10,
                                    Id = 13,
                                    Amount = 0.5,
                                    Measurement = 1,
                                    Name = "Salt"
                                },
                                new
                                {
                                    RecipeId = 10,
                                    Id = 14,
                                    Amount = 0.5,
                                    Measurement = 5,
                                    Name = "Very cold unsalted butter"
                                },
                                new
                                {
                                    RecipeId = 11,
                                    Id = 1,
                                    Amount = 4.0,
                                    Measurement = 5,
                                    Name = "Whole milk"
                                },
                                new
                                {
                                    RecipeId = 11,
                                    Id = 2,
                                    Amount = 2.0,
                                    Measurement = 3,
                                    Name = "Sugar"
                                },
                                new
                                {
                                    RecipeId = 11,
                                    Id = 3,
                                    Amount = 0.5,
                                    Measurement = 3,
                                    Name = "Vanilla bean "
                                },
                                new
                                {
                                    RecipeId = 11,
                                    Id = 4,
                                    Amount = 6.0,
                                    Measurement = 4,
                                    Name = "Dark chocolate"
                                },
                                new
                                {
                                    RecipeId = 11,
                                    Id = 5,
                                    Amount = 1.0,
                                    Measurement = 1,
                                    Name = "Sea salt"
                                },
                                new
                                {
                                    RecipeId = 11,
                                    Id = 6,
                                    Amount = 4.0,
                                    Measurement = 4,
                                    Name = "Bourbon"
                                },
                                new
                                {
                                    RecipeId = 11,
                                    Id = 7,
                                    Amount = 2.0,
                                    Measurement = 4,
                                    Name = "Frangelico"
                                },
                                new
                                {
                                    RecipeId = 11,
                                    Id = 8,
                                    Amount = 2.0,
                                    Measurement = 4,
                                    Name = "Irish cream"
                                },
                                new
                                {
                                    RecipeId = 11,
                                    Id = 9,
                                    Measurement = 12,
                                    Name = "Marshmallows"
                                },
                                new
                                {
                                    RecipeId = 12,
                                    Id = 1,
                                    Amount = 1.0,
                                    Measurement = 4,
                                    Name = "All-purpose flour"
                                },
                                new
                                {
                                    RecipeId = 12,
                                    Id = 2,
                                    Amount = 0.5,
                                    Measurement = 4,
                                    Name = "Unsweetened cocoa powder"
                                },
                                new
                                {
                                    RecipeId = 12,
                                    Id = 3,
                                    Amount = 1.0,
                                    Measurement = 1,
                                    Name = "Baking powder"
                                },
                                new
                                {
                                    RecipeId = 12,
                                    Id = 4,
                                    Amount = 0.25,
                                    Measurement = 1,
                                    Name = "Baking soda"
                                },
                                new
                                {
                                    RecipeId = 12,
                                    Id = 5,
                                    Amount = 0.25,
                                    Measurement = 1,
                                    Name = "Salt"
                                },
                                new
                                {
                                    RecipeId = 12,
                                    Id = 6,
                                    Amount = 10.25,
                                    Measurement = 1,
                                    Name = "Brown sugar"
                                },
                                new
                                {
                                    RecipeId = 12,
                                    Id = 7,
                                    Amount = 3.0,
                                    Measurement = 0,
                                    Name = "Egg"
                                },
                                new
                                {
                                    RecipeId = 12,
                                    Id = 8,
                                    Amount = 1.0,
                                    Measurement = 1,
                                    Name = "Vanilla extract"
                                },
                                new
                                {
                                    RecipeId = 12,
                                    Id = 9,
                                    Amount = 4.0,
                                    Measurement = 4,
                                    Name = "Unsweetened chocolate"
                                },
                                new
                                {
                                    RecipeId = 12,
                                    Id = 10,
                                    Amount = 4.0,
                                    Measurement = 3,
                                    Name = "Unsalted butter"
                                },
                                new
                                {
                                    RecipeId = 12,
                                    Id = 11,
                                    Amount = 0.5,
                                    Measurement = 5,
                                    Name = "Granulated sugar"
                                },
                                new
                                {
                                    RecipeId = 12,
                                    Id = 12,
                                    Amount = 0.5,
                                    Measurement = 5,
                                    Name = "Confectioners' sugar"
                                },
                                new
                                {
                                    RecipeId = 12,
                                    Id = 13,
                                    Amount = 0.75,
                                    Measurement = 5,
                                    Name = "Salted butter"
                                },
                                new
                                {
                                    RecipeId = 12,
                                    Id = 14,
                                    Amount = 3.0,
                                    Measurement = 5,
                                    Name = "Powdered sugar"
                                },
                                new
                                {
                                    RecipeId = 12,
                                    Id = 15,
                                    Amount = 3.0,
                                    Measurement = 3,
                                    Name = "Heavy cream"
                                },
                                new
                                {
                                    RecipeId = 12,
                                    Id = 16,
                                    Amount = 2.0,
                                    Measurement = 1,
                                    Name = "Peppermint extract"
                                },
                                new
                                {
                                    RecipeId = 12,
                                    Id = 17,
                                    Amount = 8.0,
                                    Measurement = 0,
                                    Name = "Peppermint candy canes"
                                });
                        });
                });

            modelBuilder.Entity("Foodie.Dal.Entities.UserRecipe", b =>
                {
                    b.HasOne("Foodie.Dal.Entities.Recipe", "Recipe")
                        .WithMany("Users")
                        .HasForeignKey("RecipeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Foodie.Dal.Entities.User", "User")
                        .WithMany("FavouriteRecipes")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<int>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole<int>", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<int>", b =>
                {
                    b.HasOne("Foodie.Dal.Entities.User", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<int>", b =>
                {
                    b.HasOne("Foodie.Dal.Entities.User", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<int>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole<int>", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Foodie.Dal.Entities.User", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<int>", b =>
                {
                    b.HasOne("Foodie.Dal.Entities.User", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
